---
title: "Literature"
output: 
  html_document:
    toc: true
    toc_float: true
    toc_depth: 5
    df_print: paged
---

This page links to diverse literature relevant to scale development and validation. It will be continuesly updated and extended. 

## Overall scale Development and Validation

- Carpenter, S. (2018). Ten Steps in Scale Development and Reporting: A Guide for Researchers. Communication Methods & Measures, 12(1), 25-33. [https://doi.org/10.1080/19312458.2017.1396583](https://doi.org/10.1080/19312458.2017.1396583)
- Fabrigar, L. R., Wegener, D. T., MacCallum, R. C., & Strahan, E. J. (1999). Evaluating the use of exploratory factor analysis in psychological research. Psychological methods, 4(3), 272. https://doi.org/10.1037/1082-989X.4.3.272
- Flake, J.K., Fried, E.I.. (2020). Measurement Schmeasurement: Questionable Measurement Practices and How to Avoid Them. Advances in Methods and Practices in Psychological Science, 3(4):456-465. https://doi.org/10.1177/2515245920952393
- Morrison, J. T. (2009). Evaluating factor analysis decisions for scale design in communication research. Communication Methods and Measures, 3(4), 195-215. https://doi.org/10.1080/19312450903378917
- Noar, S. M. (2003). The role of structural equation modeling in scale development. Structural equation modeling, 10(4), 622-647. https://doi.org/10.1207/S15328007SEM1004_8
- Worthington, R. L., & Whittaker, T. A. (2006). Scale development research: A content analysis and recommendations for best practices. The counseling psychologist, 34(6), 806-838. https://doi.org/10.1177/0011000006288127


## Overall Text books

- Bond, T. G., & Fox, C. F. (2007). Applying the Rasch model: Fundamental measurement in the human sciences (2nd
ed.). Routledge.
- DeMars, C. (2010). Item response theory. Oxford University Press.
- DeVellis, R. F., & Thorpe, C. T. (2021). Scale development: Theory and applications. Sage publications.
- Embretson, S. E., & Reise, S. P. (2013). Item response theory (2nd ed.). Psychology Press.
- McDonald, R. P. (1999). Test theory: A unified treatment. Mahwah, N.J.: L. Erlbaum Associates.
- Thissen, D., & Wainer, H. (Eds.). (2001). Test scoring. Lawrence Erlbaum Associates Publishers.

## Specific topics

- Bernstein, I. H. and Teng, G. 1989. Factoring items and factoring scales are different: Spurious evidence for multidimensionality due to item categorization. Psychological Bulletin, 105(3): 467–477.  
- Bollen, K. A. and Lennox, R. 1991. Conventional wisdom on measurement: A structural equation perspective. Psychological Bulletin, 110(2): 305–314.
- Briggs, S. R. and Cheek, J. M. 1986. The role of factor analysis in the development and evaluation of personality scales. Journal of Personality, 54(1): 106–148.
- Clark, L. A., & Watson, D. (2016). Constructing validity: Basic issues in objective scale development. In A. E. Kazdin (Ed.), Methodological issues and strategies in clinical research (pp. 187–203). American Psychological Association. https://doi.org/10.1037/14805-012
- Costello, A. B. and Osborne, J. W. 2005. Best practices in exploratory factor analysis: Four recommendations for getting the most from your analysis. Practical Assessment, Research & Evaluation, 7(10): 1–9.
- Reise, S. P. (2012). The Rediscovery of bifactor measurement models. Multivariate Behavioral Research, 47, 667–696.
- Reise, S. P., Moore, T. M. & Haviland, M. G. (2010). Bifactor models and rotations: Exploring the extent to which multidimensional data yield univocal scale scores. Journal of Personality Assessment, 92, 544–559. https://doi.org/10.1080/00223891.2010.496477
- Yung, Y. F., Thissen, D. & McLeod, L. D. (1999). On the relationship between the higher-order factor model and the hierarchical factor model. Psychometrika, 64, 113–128.
